seed: 0
device: "cuda:0"

vocabulary_size: 10000
batch_size: 32
window_size: 2
embedding_size: 200

learning_rate: 0.05
max_epochs: 20
min_loss_improvement: 0.00001
patience: 10
validation_interval: 1
